export interface JobOffer {
  id: string
  empresa: string
  empresaInicial: string
  empresaColor: string
  puesto: string
  matchPorcentaje: number
  recomendado: boolean
  dificultad: 'Baja' | 'Media' | 'Alta'
  descripcionCorta: string
  ubicacion: string
  modalidad: 'Remoto' | 'Presencial' | 'Híbrido'
  contrato: 'Tiempo Completo' | 'Medio Tiempo' | 'Practicas'
  habilidades: string[]
  sueldoMin: number
  sueldoMax: number
  postulacionAbierta: boolean
  fuente: 'LinkedIn' | 'Indeed' | 'Bumeran' | 'Computrabajo'
  porQueEsteMatch: string
  funcionesPrincipales: string[]
  habilidadesRequeridas: string[]
}

export const mockJobOffers: JobOffer[] = [
  {
    id: 'mo-1',
    empresa: 'Scotiabank Perú',
    empresaInicial: 'SCO',
    empresaColor: 'bg-red-600',
    puesto: 'Analista de Datos Junior',
    matchPorcentaje: 87,
    recomendado: true,
    dificultad: 'Baja',
    descripcionCorta: 'Transforma datos financieros en reportes estratégicos para el equipo comercial de banca personal.',
    ubicacion: 'San Isidro, Lima',
    modalidad: 'Híbrido',
    contrato: 'Tiempo Completo',
    habilidades: ['Python', 'SQL', 'Power BI'],
    sueldoMin: 2200,
    sueldoMax: 3000,
    postulacionAbierta: true,
    fuente: 'LinkedIn',
    porQueEsteMatch: 'Tu manejo de Python y SQL se alinea perfectamente con los requisitos del equipo de analítica.',
    funcionesPrincipales: [
      'Exploración y limpieza de bases de datos relacionales.',
      'Generación de dashboards ejecutivos en Power BI.',
      'Automatización de reportes diarios con scripts Python.',
    ],
    habilidadesRequeridas: ['Python intermedio', 'SQL avanzado', 'Power BI', 'Excel'],
  },
  {
    id: 'mo-2',
    empresa: 'Rappi Perú',
    empresaInicial: 'R',
    empresaColor: 'bg-orange-500',
    puesto: 'Frontend Developer Junior',
    matchPorcentaje: 82,
    recomendado: true,
    dificultad: 'Media',
    descripcionCorta: 'Desarrolla nuevas funcionalidades para la app de delivery más usada en Latinoamérica.',
    ubicacion: 'Remoto',
    modalidad: 'Remoto',
    contrato: 'Tiempo Completo',
    habilidades: ['React', 'TypeScript', 'CSS'],
    sueldoMin: 2800,
    sueldoMax: 3800,
    postulacionAbierta: true,
    fuente: 'LinkedIn',
    porQueEsteMatch: 'Dominas React y TypeScript, herramientas core del stack de Rappi para la capa frontend.',
    funcionesPrincipales: [
      'Maquetación de componentes reutilizables en React.',
      'Integración con APIs REST del backend de pedidos.',
      'Implementación de pruebas unitarias con Jest.',
    ],
    habilidadesRequeridas: ['React', 'TypeScript', 'Git', 'REST APIs'],
  },
  {
    id: 'mo-3',
    empresa: 'IBM Perú',
    empresaInicial: 'IBM',
    empresaColor: 'bg-slate-800',
    puesto: 'Backend Developer Trainee',
    matchPorcentaje: 75,
    recomendado: false,
    dificultad: 'Media',
    descripcionCorta: 'Desarrolla microservicios empresariales usando Java y Spring Boot para clientes del sector financiero.',
    ubicacion: 'Miraflores, Lima',
    modalidad: 'Presencial',
    contrato: 'Tiempo Completo',
    habilidades: ['Java', 'Spring Boot', 'Docker'],
    sueldoMin: 2500,
    sueldoMax: 3500,
    postulacionAbierta: true,
    fuente: 'Bumeran',
    porQueEsteMatch: 'Tu base en programación orientada a objetos y entendimiento de APIs REST encaja con el rol.',
    funcionesPrincipales: [
      'Diseño de endpoints REST en Spring Boot.',
      'Gestión de contenedores Docker para ambientes de desarrollo.',
      'Documentación técnica de servicios con Swagger.',
    ],
    habilidadesRequeridas: ['Java', 'Spring Boot', 'SQL', 'Docker básico'],
  },
  {
    id: 'mo-4',
    empresa: 'BCP',
    empresaInicial: 'BCP',
    empresaColor: 'bg-blue-700',
    puesto: 'Practicante QA Automation',
    matchPorcentaje: 68,
    recomendado: false,
    dificultad: 'Baja',
    descripcionCorta: 'Asegura la calidad del canal digital del banco ejecutando y automatizando pruebas de regresión.',
    ubicacion: 'San Isidro, Lima',
    modalidad: 'Híbrido',
    contrato: 'Practicas',
    habilidades: ['Selenium', 'Jira', 'SQL'],
    sueldoMin: 1500,
    sueldoMax: 1800,
    postulacionAbierta: true,
    fuente: 'Computrabajo',
    porQueEsteMatch: 'Tu conocimiento de Jira y SQL te da ventaja para reportar defectos y validar datos.',
    funcionesPrincipales: [
      'Creación de casos de prueba funcionales y de regresión.',
      'Ejecución de scripts automatizados en Selenium WebDriver.',
      'Registro y seguimiento de bugs en Jira.',
    ],
    habilidadesRequeridas: ['Selenium básico', 'Jira', 'SQL', 'Testing manual'],
  },
  {
    id: 'mo-5',
    empresa: 'Interbank',
    empresaInicial: 'IBK',
    empresaColor: 'bg-emerald-600',
    puesto: 'Analista de Marketing Digital Jr',
    matchPorcentaje: 79,
    recomendado: true,
    dificultad: 'Baja',
    descripcionCorta: 'Gestiona y optimiza campañas digitales de captación de clientes para productos financieros.',
    ubicacion: 'San Borja, Lima',
    modalidad: 'Híbrido',
    contrato: 'Tiempo Completo',
    habilidades: ['Google Ads', 'SEO', 'Meta Ads'],
    sueldoMin: 2000,
    sueldoMax: 2800,
    postulacionAbierta: true,
    fuente: 'LinkedIn',
    porQueEsteMatch: 'Tu experiencia con campañas pagadas y conocimiento de métricas digitales es el fit ideal.',
    funcionesPrincipales: [
      'Configuración y optimización de campañas en Google Ads y Meta.',
      'Análisis de métricas en Google Analytics 4.',
      'Elaboración de reportes de rendimiento semanales.',
    ],
    habilidadesRequeridas: ['Google Ads', 'Meta Ads', 'Google Analytics', 'Excel'],
  },
  {
    id: 'mo-6',
    empresa: 'Belcorp',
    empresaInicial: 'BEL',
    empresaColor: 'bg-pink-600',
    puesto: 'Practicante Finanzas Corporativas',
    matchPorcentaje: 71,
    recomendado: false,
    dificultad: 'Media',
    descripcionCorta: 'Apoya en el análisis financiero y proyecciones de negocio para las marcas del grupo en Perú.',
    ubicacion: 'Surco, Lima',
    modalidad: 'Presencial',
    contrato: 'Practicas',
    habilidades: ['Excel', 'Finanzas', 'PowerPoint'],
    sueldoMin: 1500,
    sueldoMax: 1800,
    postulacionAbierta: false,
    fuente: 'Bumeran',
    porQueEsteMatch: 'Tu formación en finanzas y manejo avanzado de Excel son las habilidades clave del rol.',
    funcionesPrincipales: [
      'Elaboración de modelos financieros en Excel.',
      'Apoyo en la preparación de reportes para directivos.',
      'Análisis de variaciones de presupuesto vs real.',
    ],
    habilidadesRequeridas: ['Excel avanzado', 'Finanzas básicas', 'PowerPoint', 'Análisis de datos'],
  },
  {
    id: 'mo-7',
    empresa: 'Rimac Seguros',
    empresaInicial: 'RIM',
    empresaColor: 'bg-purple-600',
    puesto: 'Junior Data Engineer',
    matchPorcentaje: 83,
    recomendado: true,
    dificultad: 'Alta',
    descripcionCorta: 'Construye y mantiene pipelines de datos para alimentar modelos analíticos del área actuarial.',
    ubicacion: 'Remoto',
    modalidad: 'Remoto',
    contrato: 'Tiempo Completo',
    habilidades: ['Python', 'Airflow', 'SQL'],
    sueldoMin: 3000,
    sueldoMax: 4000,
    postulacionAbierta: true,
    fuente: 'LinkedIn',
    porQueEsteMatch: 'Tu experiencia con Python para ETL y fundamentos de bases de datos te hace un candidato sólido.',
    funcionesPrincipales: [
      'Diseño de pipelines de ingesta de datos con Apache Airflow.',
      'Transformación y validación de datos con Python y Pandas.',
      'Mantenimiento del Data Warehouse en Redshift.',
    ],
    habilidadesRequeridas: ['Python', 'SQL avanzado', 'Airflow', 'Cloud (AWS/GCP)'],
  },
  {
    id: 'mo-8',
    empresa: 'Falabella Perú',
    empresaInicial: 'FAL',
    empresaColor: 'bg-green-700',
    puesto: 'Practicante Logística Ecommerce',
    matchPorcentaje: 64,
    recomendado: false,
    dificultad: 'Baja',
    descripcionCorta: 'Apoya en el seguimiento y optimización de rutas de última milla para despachos del portal online.',
    ubicacion: 'Surco, Lima',
    modalidad: 'Presencial',
    contrato: 'Practicas',
    habilidades: ['Excel', 'Logística', 'Power BI'],
    sueldoMin: 1500,
    sueldoMax: 1700,
    postulacionAbierta: true,
    fuente: 'Computrabajo',
    porQueEsteMatch: 'Tu conocimiento en gestión de cadena de suministro y Excel te da base suficiente para el puesto.',
    funcionesPrincipales: [
      'Seguimiento de indicadores de entrega (OTD, OTIF).',
      'Actualización de tableros logísticos en Power BI.',
      'Coordinación con transportistas para solución de incidencias.',
    ],
    habilidadesRequeridas: ['Excel intermedio', 'Power BI básico', 'Logística', 'Comunicación'],
  },
  {
    id: 'mo-9',
    empresa: 'Globant Perú',
    empresaInicial: 'GLO',
    empresaColor: 'bg-teal-600',
    puesto: 'Junior Cloud Engineer',
    matchPorcentaje: 91,
    recomendado: true,
    dificultad: 'Alta',
    descripcionCorta: 'Despliega y administra infraestructura cloud para proyectos de clientes internacionales en AWS.',
    ubicacion: 'Miraflores, Lima',
    modalidad: 'Remoto',
    contrato: 'Tiempo Completo',
    habilidades: ['AWS', 'Terraform', 'Docker'],
    sueldoMin: 3500,
    sueldoMax: 4500,
    postulacionAbierta: true,
    fuente: 'LinkedIn',
    porQueEsteMatch: 'Dominas AWS y Terraform a nivel funcional, que son exactamente los pilares del stack de infraestructura en Globant.',
    funcionesPrincipales: [
      'Aprovisionamiento de infraestructura AWS con Terraform.',
      'Configuración de pipelines CI/CD en GitHub Actions.',
      'Monitoreo de recursos cloud con CloudWatch y alertas.',
    ],
    habilidadesRequeridas: ['AWS', 'Terraform', 'Docker', 'Linux', 'CI/CD'],
  },
  {
    id: 'mo-10',
    empresa: 'Indra Perú',
    empresaInicial: 'IND',
    empresaColor: 'bg-blue-900',
    puesto: 'Analista Funcional Junior',
    matchPorcentaje: 76,
    recomendado: true,
    dificultad: 'Media',
    descripcionCorta: 'Levanta requerimientos y define especificaciones técnicas para proyectos de transformación digital bancaria.',
    ubicacion: 'San Isidro, Lima',
    modalidad: 'Híbrido',
    contrato: 'Tiempo Completo',
    habilidades: ['UML', 'Scrum', 'SQL'],
    sueldoMin: 2500,
    sueldoMax: 3200,
    postulacionAbierta: true,
    fuente: 'Bumeran',
    porQueEsteMatch: 'Tu capacidad analítica y conocimiento en metodologías ágiles encajan con el rol de puente entre negocio y TI.',
    funcionesPrincipales: [
      'Elaboración de historias de usuario y criterios de aceptación.',
      'Modelado de flujos de proceso con diagramas UML.',
      'Coordinación de pruebas de aceptación con usuarios finales (UAT).',
    ],
    habilidadesRequeridas: ['UML', 'Scrum', 'SQL básico', 'Documentación técnica'],
  },
]
